# Default values for my-ghost-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghost
  tag: 2.6-alpine
  pullPolicy: Always

volume:
  metadataName: blog-content
  claimName: blog-content
  name: content
  mountPath: /var/lib/ghost/content
  accessModes: ReadWriteOnce
  storage: 5Gi
  storageClassName: do-block-storage

service:
  type: LoadBalancer
  port: 80
  targetPort: 2368
