apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-ghost-chart.fullname" . }}
  labels:
    {{- include "my-ghost-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "my-ghost-chart.selectorLabels" . | nindent 4 }}
